python/lib/sift_py/__init__.py, python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/_internal/ingest_test.py, python/lib/sift_py/ingestion/_internal/ingestion_config.py, python/lib/sift_py/ingestion/_service_test.py, python/lib/sift_py/ingestion/channel.py, python/lib/sift_py/ingestion/manager.py, python/lib/sift_py/ingestion/service.py
This PR adds the ability to register a new flow during run-time in an ergonomic manner as well as introducing a multi-telemetry-config manager to be able to telemeter for multiple assets or configs.
```python
manager = IngestionServicesManager.from_telementry_configs(grpc_channel, {
"config_a": config_a,
"config_b": config_b,
})
with manager.ingestion_service("config_a") as config_a:
config_a.try_ingest_flow(...)
with manager.ingestion_service("config_b") as config_b:
config_b.try_ingest_flow(...)
```
=> python(feature): multi-asset ingestion + automatic flow updates

python/CHANGELOG.md, python/lib/sift_py/__init__.py, python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/_service_test.py, python/lib/sift_py/ingestion/service.py, python/pyproject.toml
Changelog + documentation updates. Preparing for `v0.1.0-rc.2`.
=> python(chore): changelog for rc.2

python/lib/sift_py/grpc/_interceptors.py, python/lib/sift_py/grpc/_retry.py, python/lib/sift_py/grpc/transport.py, python/lib/sift_py/grpc/transport_test.py, python/pyproject.toml
This PR adds support for automated retries using gRPC's retry mechanism should an RPC fail and return any of the following status codes:
- `UNKNOWN`
- `UNAVAILABLE`
- `ABORTED`
- `DEADLINE EXCEEDED`
These status codes were chosen on the basis that they are not explicitly set by Sift and often occur due to some external factor. Here is the retry policy that is introduced in this PR:
```python
DEFAULT_POLICY: RetryConfig = {
"methodConfig": [
{
"name": [{}],
"retryPolicy": {
"maxAttempts": 5,
"initialBackoff": "0.1s",
"maxBackoff": "1s",
"backoffMultiplier": 2,
"retryableStatusCodes": [
StatusCode.UNKNOWN.name,
StatusCode.UNAVAILABLE.name,
StatusCode.ABORTED.name,
StatusCode.DEADLINE_EXCEEDED.name,
],
},
}
]
}
```
Users may be given the ability to customize retry policies in the future, but …
=> python(feature): automate gRPC retries

python/lib/sift_py/grpc/keepalive.py, python/lib/sift_py/grpc/transport.py
Support keepalive for `SiftChannel` for HTTP2 keepalive-pings.
=> python(feature): support keepalive

python/lib/sift_py/ingestion/channel.py
This PR adds the ability to generate a channel value directly from a channel config based on data-type.
=> python(feature): generate channel value from channel config

python/lib/sift_py/ingestion/_service_test.py, python/lib/sift_py/ingestion/buffer.py, python/lib/sift_py/ingestion/service.py
This PR adds support for timeout-based flushing for buffered ingestion. Users can now configure an interval in which a buffer will get flushed regardless of whether or not the buffer has been filled. If a buffer is flushed due to being filled, the timer gets restarted.
Additionally, this PR introduces the ability to customize `__exit__` behavior when using the buffered ingestion API in a context manager when there is an error.
=> python(feature): timeout-based flushing for buffered ingestion

python/lib/sift_py/ingestion/channel.py
A check for the double channel data type was omitted from method that produced a channel value from a channel config.
=> python(fix): add missing double channel computation

.gitignore, .vscode/settings.json, python/examples/ingestion_with_python_config/rule_modules/velocity.yml, python/examples/ingestion_with_python_config/rule_modules/voltage.yml, python/examples/ingestion_with_python_config/telemetry_config.py, python/examples/ingestion_with_yaml_config/rule_modules/velocity.yml, python/examples/ingestion_with_yaml_config/rule_modules/voltage.yml, python/examples/ingestion_with_yaml_config/telemetry_config.py, python/examples/ingestion_with_yaml_config/telemetry_configs/nostromo_lv_426.yml, python/lib/sift_py/ingestion/config/telemetry.py, python/lib/sift_py/ingestion/config/telemetry_test.py, python/lib/sift_py/ingestion/config/yaml/load.py, python/lib/sift_py/ingestion/config/yaml/spec.py, python/lib/sift_py/ingestion/config/yaml/test_load.py, python/lib/sift_py/ingestion/rule/config.py, python/lib/sift_py/ingestion/rule/config_test.py
This PR adds the ability to define rules in YAML separate from the main telemetry config, so that rules may be referenced and reused in the context of multiple assets.
A rule that's defined in a namespace can be referenced in the main telemetry config like so:
```
- namespace: voltage
name: undervoltage
channel_references:
- $1: *vehicle_state_channel
- $2: *voltage_channel
```
With the corresponding rule defined in a separate YAML like so:
```
namespace: voltage
- name: undervoltage
description: Checks for undervoltage while accelerating
expression: $1 == "Accelerating" && $2 < 40
type: review
```
Or if the user wants to instantiate rules in python directly, the `load_rule_namespaces` function has been added that will allow them to provide a path to the directory containing their rule …
=> feat: Asset agnostic rule configs

python/lib/sift_py/data/service.py
There was a logic error in how we retrieve channel information from the channel cache in the data service. Essentially if the channel is in the cache we end up passing an empty list to the `ChannelService_ListChannels` endpoint which then returns an error response causing an exception to be raised. This PR fixes that.
This branch was created from the latest commit in this [0.2.2 tag](https://github.com/sift-stack/sift/commits/python/v0.2.2) and once merged, it will sit immediately after that commit. This is so that we can create a patch release version bump that doesn't contain all the things we're intending to keep in `0.3`. I will do a merge commit for this.
=> python(bug): fix download bug for same channel requested

python/lib/sift_py/file_attachment/__init__.py, python/lib/sift_py/file_attachment/metadata.py
Tested locally with:
```
remote_file = file_attachment_service.upload_attachment(
path="/Users/mjulien/Downloads/Short3.mp4",
entity=run,
metadata=VideoMetadata(height=2160, width=3840, duration_seconds=28, timestamp=datetime(2024, 10, 19, 2, 22, 22, tzinfo=timezone.utc)),
description="thrusters getting too hot" ,
)
```
=> python(feat): Add timestamp arg to VideoMetadata

.github/workflows/python_ci.yaml, python/lib/sift_py/grpc/transport.py, python/lib/sift_py/grpc/transport_test.py, python/pyproject.toml, python/scripts/dev
Implements [this workaround](https://github.com/grpc/grpc/issues/29682#issuecomment-2347888481) optionally if the OpenSSL dependency is installed.
=> feat: Add ssl credentials workaround with optional OpenSSL import

rust/Cargo.toml
Fixes this github actions error: https://github.com/sift-stack/sift/actions/runs/11806687616/job/32891898758
=> rust(build): remove keyword from project metadata

python/examples/ping/.env-example, python/examples/ping/main.py, python/examples/ping/requirements.txt
Simple ping example to use in public docs
=> python(chore): ping example

python/lib/sift_py/data/_service_test.py, python/lib/sift_py/data/service.py, rust/examples/ingestion/main.rs
- Channels with `.` in their name experienced issues downloading data due to how channel names were handled. This PR fixes that.
Unit testing and manual verification:
=> python(bug): fix data download bug for channels with '.' delimited name

.github/workflows/python_build.yaml, .github/workflows/python_release.yaml, python/pyproject.toml, python/scripts/build_utils.py
Some users wish to install `sift-stack-py` without access to pypi. 
This PR adds a new workflow `python_build.yaml` that builds offline installation archives (wheels for each dependency) that target all supported python versions and various platforms (linux, mac, windows) and architectures (e.g. x86_64/arm64).
Users will be able to install `sift-py-stack` by running `pip install sift-py-stack --no-index --find-links {path/to/offline-installation-archive}`. 
Ran `python_release.yaml` workflow which calls the new `python_build.yaml` on a dev tag and successfully created a release
https://github.com/sift-stack/sift/actions/runs/12273019715
Manually downloaded and inspected archives as well as installing locally on my mac.
=> python(feat): Add offline installation archives for various platforms

python/lib/sift_py/grpc/keepalive.py, python/lib/sift_py/grpc/transport.py
- HTTP/2 keep-alive was an opt-in feature but many users weren't aware of it so now making it default with an option to disable or provide custom keep-alive.
- Configure a custom user-agent so we can track client library usage an addition to helping assist with debugging.
The impetus for this was that some users were experiencing timeouts while downloading data from the data API. For long time ranges connections are idle which makes them subject to the LB's idle connection timeout. Keep-alive will automate the gRPC client sending HTTP/2 ping frames to keep the connection alive.
=> python(feat): enable keepalive by default and configure user-agent

.github/workflows/python_ci.yaml, python/examples/data_import/tdms/requirements.txt, python/lib/sift_py/data_import/__init__.py, python/lib/sift_py/data_import/tdms.py, python/pyproject.toml
The `npTDMS` arg should not be required for the standard lib, but included as an optional dep for users who do use the lib to manage TDMS data. Users can include `sift-stack-py[tdms]` in their project dependencies if TDMS is required.
=> python(chore): Make npTDMS an optional dep

python/examples/ingestion_with_csv/single_csv/main.py, python/lib/sift_py/data_import/ch10.py, python/lib/sift_py/data_import/csv.py, python/lib/sift_py/data_import/tdms.py, python/lib/sift_py/data_import/tempfile.py, python/scripts/build_utils.py
Use custom NamedTemporaryFile that is windows compatible.
Before:
```
marc@marc-windows MINGW64 ~/code/sift/python/examples/data_import/tdms (python/fix-windows-imports)
$ python  main.py
Traceback (most recent call last):
File "C:\Users\marc\code\sift\python\examples\data_import\tdms\main.py", line 29, in <module>
import_service = tdms_upload_service.upload(
"sample_data.tdms", asset_name, group_into_components=True
)
File "C:\Users\marc\code\sift\python\lib\sift_py\data_import\tdms.py", line 81, in upload
valid_channels = self._convert_to_csv(path, temp_file.name, ignore_errors)
File "C:\Users\marc\code\sift\python\lib\sift_py\data_import\tdms.py", line 140, in _convert_to_csv
with TdmsWriter(f.name) as tdms_writer:
~~~~~~~~~~^^^^^^^^
File …
```
=> python(bugfix): fix tempfile issues on windows

python/lib/sift_py/data_import/_tdms_test.py, python/lib/sift_py/data_import/tdms.py
TDMS example ran without uploading parameters in the description:
```
$ python main.py
data_import_id='21eea37a-140f-44d1-85b0-92cea35553c2' created_date=datetime.datetime(2025, 1, 24, 20, 16, 56, 234293, tzinfo=TzInfo(UTC)) 
...
'description': 'Description for channel channel_0',  
...
Upload example complete!
```
=> python(bug): Don't upload tdms channel properties

python/lib/sift_py/rule/config.py
Fix bug where RuleActionAnnotationKind.from_annotation_type() only returns a PHASE type.
=> python: Fix rule config `from_annotation_type`

python/examples/ingestion_with_python_config/main.py, python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/service.py
Removes the previously deprecated argument `overwrite_rules` from the `IngestionService`.
=> python(feat): remove overwrite_rules argument from ingestion service

python/examples/report_templates/report_template_with_python_config/main.py, python/examples/report_templates/report_template_with_python_config/report_template_config.py, python/examples/report_templates/report_template_with_yaml_config/main.py, python/lib/sift_py/calculated_channels/config.py, python/lib/sift_py/report_templates/_config_test.py, python/lib/sift_py/report_templates/_service_test.py, python/lib/sift_py/report_templates/config.py, python/lib/sift_py/report_templates/service.py
This PR adds:
- A `ReportTemplateUpdate` class to allow users to easily specify update fields
- Updates the `ReportTemplateService` to specify only the fields actually being updated in the `FieldMask` passed back to the API
- Updates the ReportTemplate examples accordingly
- Updates the relevant unit tests
=> fix: ReportTemplate updates provide FieldMask keys based on what needs to be updated

python/lib/sift_py/rest.py
This implementation is based on https://stackoverflow.com/a/77577017
Tested this by spinning up a local HTTP server with custom certs. I found instructions to create a custom cert for localhost and add it to openssl's CA store. Then I created an HTTPServer using the same cert:
```
import http.server
import ssl
server_address = ('localhost', 4443)
httpd = http.server.HTTPServer(server_address, http.server.SimpleHTTPRequestHandler)
context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
context.load_cert_chain(certfile="cert.pem", keyfile="key.pem")
httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
print("Serving on https://localhost:4443")
httpd.serve_forever()
```
Used the following config with the CsvUploadService example:
```
rest_config: SiftRestConfig = {
"uri": …
```
=> python(feature): Allow using openssl certs with REST

.github/workflows/go_release.yaml
I couldn't figure out how to get `act` to use a different tag, but with the tag that it was using I can see that the variable is being set correctly unlike before:
Before:
```
...
[Go Module Publish/publish-to-pkg-go-dev]   🐳  docker exec cmd=[bash -e /var/run/act/workflow/3] user= workdir=
| go: github.com/sift-stack/sift/go@: invalid version: disallowed version string
...
```
After:
```
...
[Go Module Publish/publish-to-pkg-go-dev]   🐳  docker exec cmd=[bash -e /var/run/act/workflow/3] user= workdir=
| go: github.com/sift-stack/sift/go@sift_proxy/v1.0.0: invalid version: version "sift_proxy/v1.0.0" invalid: disallowed version string
...
```
=> go(chore): Fix workflow file

python/lib/sift_py/ingestion/channel.py
Trying to convert a bool to its prototype-type fails due to a fault in our type-checking logic. This PR fixes that.
=> python(bug): fix bool conversion

protos/sift/protobuf_descriptors/v2/protobuf_descriptors.proto
Add new endpoint to the `ProtobufDescriptorService` that allows users to check protobuf descriptor compatibility.
=> protos(feature): protobuf desc compatibility check

python/lib/sift_py/rule/service.py
Fixes the issue where rules created by the RuleService had an unknown annotation type.
=> fix(python): RuleService adds annotation type

python/examples/ingestion_with_no_buffering/.env-example, python/examples/ingestion_with_no_buffering/main.py, python/examples/ingestion_with_no_buffering/requirements.txt, python/examples/ingestion_with_no_buffering/rule_modules/velocity.yml, python/examples/ingestion_with_no_buffering/rule_modules/voltage.yml, python/examples/ingestion_with_no_buffering/simulator.py, python/examples/ingestion_with_no_buffering/telemetry_config.py, python/examples/ingestion_with_threading/main.py, python/examples/ingestion_with_threading/requirements.txt, python/examples/ingestion_with_threading/rule_modules/velocity.yml, python/examples/ingestion_with_threading/rule_modules/voltage.yml, python/examples/ingestion_with_threading/simulator.py, python/examples/ingestion_with_threading/telemetry_config.py, python/lib/sift_py/ingestion/buffer.py
Added an example that handles ingestion in a separate thread to prevent data generating from being blocked.
This example is a copy/paste of the `ingestion_with_python_config`. Changes were made to main.py and some small changes to simulator.py.
Also added an example that does true streaming using a generator. This example is a copy/paste of the `ingestion_with_python_config`. Changes were made to main.py and some small changes to simulator.py.
Example output:
```
$ python main.py
INFO:simulator:Beginning simulation for 'NostromoLV426' with run (7adb1d3a-79c6-43ab-95b1-bbc08c4f9d56)
INFO:__main__:Opening connection and streaming for 60s
INFO:__main__:Connection closed. Data streamed successfully
INFO:__main__:Opening connection and streaming for 60s
INFO:simulator:Completed simulation. …
```
=> python(bug): Add threaded and generator ingestion example

.github/workflows/rust_release.yaml, .github/workflows/rust_release_dry_run.yaml, README.md, rust/CHANGELOG.md
Updated the existing GHA workflows to publish our new Rust crates. Also updated the CHANGELOG for our Rust crates with advice on how to migrate from the previous `sift_rs` release candidate to the new minor version we're about to release.
=> rust(build): update GHA release workflows + changelog

rust/crates/sift_stream/README.md
- Updates a link in the `sift_stream` README to use the full link rather than a relative path. The former works well on Github but [docs.rs](https://docs.rs/crate/sift_stream/0.1.0) doesn't know how to handle that which results in a broken link.
=> rust(docs): update link in README

protos/sift/data/v1/data.proto, protos/sift/data/v2/data.proto, protos/sift/protobuf_descriptors/v2/channel_parsing_options.proto
Changes:
* add BytesValues to GetDataResponse
* re-word store_message_as_bytes for clarity
=> protos: add BytesValues to GetDataResponse

rust/CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml, rust/crates/sift_connect/Cargo.toml, rust/crates/sift_error/Cargo.toml, rust/crates/sift_rs/Cargo.toml, rust/crates/sift_stream/Cargo.toml, rust/crates/sift_stream/src/backup/disk/mod.rs, rust/crates/sift_stream/src/stream/builder.rs, rust/crates/sift_stream/src/stream/mod.rs, rust/crates/sift_stream/src/stream/mode/ingestion_config.rs, rust/crates/sift_stream/src/stream/mode/test.rs, rust/crates/sift_stream/tests/test_ingestion_config_streaming_ingestion.rs
This PR introduces a few small changes:
- [The method to decode a backup is now public](https://github.com/sift-stack/sift/commit/4926ec02b9fc6ca40f503107aa586ffcab18a7ee). This is so that users can write their own programs to re-ingest backup files.
- `SiftStreamBuilder` can now attach runs by run ID.
- When attaching a run using `RunForm`, `Optional` fields that are `None` will not cause corresponding fields to zero out in Sift.
- Allows users to use raw protobuf ingestion requests to send to `SiftStream`
- Allows users to access attached run via `SiftStream`
Additional changes:
- All crates will inherit the work space version
- All crates that depend on one another will reference the workspace dependency definition.
This PR also bumps crates from `v0.1.0` -> `v0.2.0`. Once this is …
=> rust(enhancements): public backup decoding, specify run by ID, selective run field updates, allow raw ingest request

rust/CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml, rust/crates/sift_rs/Cargo.toml, rust/crates/sift_stream/Cargo.toml
This PR downgrades `chrono` from `0.4.40` to `0.4.39` due to function name collisions between `chrono` and the `arrow` crate. The recommendation right now is for folks to pin to `0.4.39`. See this issue for further details: https://github.com/apache/arrow-rs/issues/7196
Once this is merged, we do a patch bump and release `0.2.1`.
=> rust(build): downgrade chrono due to arrow crate function name conflict

python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/_internal/ingest_test.py, python/lib/sift_py/ingestion/service.py
When using [`FlowOrderedChannelValues`](https://github.com/sift-stack/sift/blob/b6fc5fdefda9718850b03da6303944de6db30c90/python/lib/sift_py/ingestion/flow.py#L64) for ingestion ([for example](https://github.com/sift-stack/azimuth/blob/main/customer/mach_industries/scripts/ulog/ulg_buffered_stream.py#L104)) the client side validation the ingestion service implements for `try_create_ingestion_request` cannot handle `channel_values` already being provided as a `List[IngestWithConfigDataChannelValue]`. 
We can still do client side validation here by ensuring the types provided in the `FlowOrderedChannelValues` aligns with the data types expected in the flow config though. So this change will make it so `try_create_ingestion_request` will:
- Try to fetch the fully qualified channel name (the …
=> python(fix): Buffered ingestion try_create_ingestion_request handles FlowOrderedChannelValues

python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/_internal/ingest_test.py, python/lib/sift_py/ingestion/_service_test.py
Originally, this only initialized with flows from the `TelemetryConfig` while ignoring any flows that may have been added at runtime with `create_flows` or `try_create_flows`.
I added some additional flows previously to running this:
```
ingestion_service = IngestionService(
channel,
telemetry_config,
end_stream_on_error=True, 
)
print(ingestion_service.flow_configs_by_name)
```
Before this change it only listed the flows in the TelemetryConfig:
```
{'readings': <sift_py.ingestion.flow.FlowConfig object at 0x10439eba0>, 'voltage': <sift_py.ingestion.flow.FlowConfig object at 0x10479c410>, 'gpio_channel': <sift_py.ingestion.flow.FlowConfig object at 0x10479c550>, 'logs': <sift_py.ingestion.flow.FlowConfig object at 0x1047a02b0>}
```
After this change it list all flows that have been added: …
=> python(bug): Fix IngestService bugs

protos/sift/protobuf_descriptors/v2/channel_parsing_options.proto
update description of the `store_message_as_bytes` FieldOption to reflect the fact that it can be used on lists and maps now
=> protos: update store_message_as_bytes description

python/lib/sift_py/ingestion/_internal/ingest_test.py, python/lib/sift_py/ingestion/_internal/ingestion_config.py
Fall back to using 1 page when getting flows from an ingestion config.
I created a large ingestion config then ran the following to retrieve and print out the number of flows in that config:
```
if __name__ == "__main__":
load_dotenv()
channel_config: SiftChannelConfig = {
"apikey": os.getenv("SIFT_API_KEY"),
"uri": os.getenv("BASE_URI"),
}
with use_sift_channel(channel_config) as channel:
print(len(get_ingestion_config_flows(channel, "8613786e-b42f-4afc-9a6e-ec4c4cdbc5d3")))
```
Before, we get this resource exhaustion error:
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.RESOURCE_EXHAUSTED
details = "CLIENT: Received message larger than max (14898020 vs. 4194304)"
debug_error_string = "UNKNOWN:Error received from peer …
```
=> python(bugfix): add fallback when retrieving flows

.github/workflows/sift_stream_bindings_release.yaml
This is the same action we use to publish the rest of our python packages, using pypi's [trusted publishing](https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#trusted-publishing) implementation so we don't need to set up separate pypi API tokens for our projects. 
It looks like this action was recently updated to work with and be [tested against maturin projects](https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.12.3) as well.
=> build(sift-stream-bindings): Use trusted publishing process to publish

.github/workflows/sift_stream_bindings_release.yaml
Unlike our other python releases that download a single named artifact where we've manually bundled all the wheels, this workflow currently uploads artifacts that contain the wheels for each os/arch, and since we're downloading all of the artifacts instead of a single named artifact, the wheels are not present in the dist/ directory but rather in subdirectories. We can manually extract the zips and put everything in the dist/ directory where the publishing artifacts expects them.
=> fix: Manually extract sift-stream-bindings artifacts for upload

.github/workflows/sift_stream_bindings_release.yaml
The artifact zips are already extracted into subdirs, so we just need to copy them into a dir the publish action can upload from: https://github.com/sift-stack/sift/actions/runs/15788760455/job/44511080583#step:3:17
=> fix: Copy artifacts from subdirs into dist

.github/workflows/sift_stream_bindings_release.yaml
Previously this worked when artifacts were downloaded to dist: https://github.com/sift-stack/sift/actions/runs/15786779218/job/44505916179#step:3:19
But we're using the `artifacts` subdir now.
=> fix: Attestation should look into artifacts dir

python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/service.py
Added an optional flag to attach_run() named `force_new`, which when true, forces creation of a new run even if an existing run of the same name exists. Defaults to False to match the existing behavior of the function.
Equivalent to running sift_py.ingestion._internal.run.create_run(), but consistent with the existing public interface.
**Verification:**
Ran the following simplified code snippet to verify a new run is attached despite a duplicate run name.
```
def test_attach_run(grpc_channel, config, run_name, force_new=False):
logging.info(f"Attach run {run_name}")
ingestion_service = IngestionService(grpc_channel, config)
ingestion_service.attach_run(grpc_channel, run_name, force_new=force_new)
write_data(ingestion_service)
logging.info(f"Now using run_id {ingestion_service.run_id}") …
```
=> python(feat): Add public method for creating new run

rust/crates/sift_stream/Cargo.toml, rust/crates/sift_stream/src/stream/mode/ingestion_config.rs
Each instance of `SiftStream` now comes with a unique ID that gets emitted whenever `SiftStream` emits logs. This is useful for environments that stream with multiple instances of `SiftStream`.
=> rust(enhancement): add unique ID to each instance of sift stream

rust/Cargo.toml
Restore explicit versions for each crate in workspace. `crates.io` is strict about this.
=> rust(build): restore explicit versions for crates in workspace

rust/CHANGELOG.md
v0.4.1 -> v0.4.2 typo in changelog
=> rust(chore): fix changelog

python/lib/sift_py/rule/_service_test.py, python/lib/sift_py/rule/config.py, python/lib/sift_py/rule/service.py
Fixes potential error when making updates to a rule by ensuring `rule_id` is always passed to `UpdateRuleRequest`
```
with use_sift_channel(sift_channel_config) as channel:
rule_service = RuleService(channel)
rule_service.create_or_update_rules(rules)
for rule in rules:
rule_service.attach_asset(rule, ["asset-2"])
```
Would previously cause an `_InactiveRpcError` due to `UpdateRuleRequest` being sent without an `rule_id`. Successfully runs with fix, and rule is updated as expected in Sift.
=> python(fix) Include rule_id when updating rule

python/lib/sift_py/_internal/time.py, python/lib/sift_py/rule_evaluation/_service_test.py, python/lib/sift_py/rule_evaluation/service.py
This change adds support for specifying start and end times with evalutating rules against a run.
=> python(feat): Add support for start and end times to rule evaluation

python/lib/sift_py/data_import/tempfile.py
PermissionError can happen when another program (like a virus scanner) is reading the file and we try to close it. Since removing the file is not critical, we should not throw an error. The file will be removed by the operating system's temp file retention policies.
=> python(bug): Catch PermissionError when removing temp files.

python/lib/sift_py/ingestion/_internal/channel.py
Fixes bug with UpdateRuleRequest
Successfully created rule that failed previously when UpdateRuleRequest received ChannelReferences with the channel name split between the name and depreciated component fields
=> python(fix): Use name only in ChannelReference creation

protos/sift/protobuf_descriptors/v2/protobuf_descriptors.proto
Adds the string field "field_kind" to the `IncompatibleProtobufField` message definition.
This new field helps indicate the "kind" (or type) of the incompatible field; when an incompatible type change is found, this new field also includes what the field type previously was to help drive corrective actions.
=> protos: Add 'field_kind' to the IncompatibleProtobufField message

python/lib/sift_py/data_import/hdf5.py
Fix bug with Hdf5UploadService on windows. Previous version would show a `file encoding is not UTF-8` error.
Recreated bug on windows platform. Fix removes bug, and files can now be uploaded.
=> python(fix): hdf5 windows fix

python/lib/sift_py/error.py, python/lib/sift_py/ingestion/_internal/ingest.py, python/lib/sift_py/ingestion/_internal/ingestion_config.py, python/lib/sift_py/ingestion/_service_test.py, python/lib/sift_py/ingestion/service.py
Implements lazy flow creation for the IngestionService.
Lazy flow creation registers the telemetry config at IngestionService initialization without any flow configs. Flow configs are registered only upon initial ingestion of that flow. This amortizes flow config registration over time, allowing very large telemetry configs which previously would have reached the maximum gRPC message size, and reducing the time needed for initilization of the IngestionService for larger configs.
By default, smaller telemetry configs will continue to be initialized up front. A `force_lazy_flow_ingestion` flag can be set to true at IngestionService initialization to force this behavior for smaller configs.
**4 asset sizes**
- Small: 2 flows, 5 channels each
- Medium: 20 flows, 50 channels each
- Large: 200 …
=> python(feat): lazy flow creation

python/lib/sift_py/_internal/metadata.py, python/lib/sift_py/data_import/_tdms_test.py, python/lib/sift_py/data_import/csv.py, python/lib/sift_py/data_import/hdf5.py, python/lib/sift_py/data_import/tdms.py
Add flag to ingest TDMS file properties as Sift Run metadata.
=> python(feat): Upload TDMS metadata to Sift Runs

rust/crates/sift_error/src/lib.rs, rust/crates/sift_rs/src/wrappers/assets.rs, rust/crates/sift_rs/src/wrappers/metadata.rs, rust/crates/sift_rs/src/wrappers/mod.rs, rust/crates/sift_rs/src/wrappers/runs.rs, rust/crates/sift_stream/examples/quick-start/main.rs, rust/crates/sift_stream/src/stream/builder.rs, rust/crates/sift_stream/src/stream/run.rs, rust/crates/sift_stream_bindings/src/stream/config.rs
- Adds ability to include metadata in SiftStream when creating a run with a new `RunForm` field `metadata`.
- Adds `add_asset_metadata()` and `add_asset_tags()` to `SiftStreamBuilder` which can be used to add tags or metadata to an asset.
- Fixes bug with existing `RunForm` tag field which did not correctly replace tags on a run if the run had existing tags
- Adds metadata macro to `sift_rs` to improve QoL when creating metadata
**Example usage for a run**
```
// Create metadata using the metadata macro
let metadata = metadata![
("test_number", 5.0),
("is_simulation", true),
("location", "SiftHQ"),
];
// Define an optional run to group together data for this period of telemetry ingestion.
let run = RunForm {
name: format!("[MarsRover0].{ts}"),
client_key: format!("mars-rover-sim-{ts}"), …
```
=> rust(feat): Run and Asset Tags and Metadata

rust/CHANGELOG.md, rust/Cargo.lock, rust/Cargo.toml
Bumping rust libraries to 0.6.0. Details in CHANGELOG.md
=> rust(chore) v0.6.0

.github/workflows/rust_ci.yaml, .github/workflows/rust_release.yaml, .github/workflows/rust_release_dry_run.yaml
Update publish workflows to use new --workspace feature in rust 1.90 and fix broken automation. Add ability to target specific tag/sha
Dry run verified to work. Publish _should_ work, but can't be tested except on main due to Action restrictions
=> rust(chore) Updated github action workflow

rust/Cargo.lock, rust/crates/sift_stream/Cargo.toml, rust/crates/sift_stream/benches/message_to_ingest_req.rs, rust/crates/sift_stream/src/stream/mode/bench.rs, rust/crates/sift_stream/src/stream/mode/ingestion_config.rs, rust/crates/sift_stream/src/stream/mode/mod.rs
* Optimizes the `message_to_ingest_req` function.
* Adds benchmarking infrastructure used for optimizing the `message_to_ingest_req` function.
* Adds "unstable" feature flag needed to support benchmarking a non-public function.
For a flow of 5000 channels, local benchmarks indicate the `message_to_ingest_req` performance has gone from taking on average 167ms to 75us, showing substantial improvements (many orders of magnitude).
The benchmark can be ran with the following cargo command:
```shell
cargo bench --bench message_to_ingest_req --features unstable
``` 
The behavior of the function remains unchanged, so existing tests still properly validate expectations.
=> rust(feat): Optimize flow conversion into gRPC request.

rust/Cargo.lock, rust/crates/sift_error/src/lib.rs, rust/crates/sift_error/src/test.rs, rust/crates/sift_stream/Cargo.toml, rust/crates/sift_stream/src/backup/disk/async_manager.rs, rust/crates/sift_stream/src/backup/test.rs, rust/crates/sift_stream/src/lib.rs, rust/crates/sift_stream/src/metrics/mod.rs, rust/crates/sift_stream/src/metrics/server.rs, rust/crates/sift_stream/src/stream/builder.rs, rust/crates/sift_stream/src/stream/mod.rs, rust/crates/sift_stream/src/stream/mode/ingestion_config.rs, rust/crates/sift_stream/tests/test_ingestion_config_streaming_checkpointing.rs, rust/crates/sift_stream/tests/test_ingestion_config_streaming_ingestion.rs, rust/crates/sift_stream/tests/test_ingestion_config_streaming_retries.rs
Adds more comprehensive metrics to SiftStream and the ability for users to access those metrics.
- Metrics are all atomics, making updating them non-blocking, and are designed to have a negligible impact on performance
- Accessing metrics by the user is non-blocking for SiftStream
- Metrics are currently gated behind the `metrics-unstable` feature flag. This is primarily driven by the need to update metrics in the near future in likely API breaking ways
- Users can access metrics directly from a SiftStream instance through the get_metrics_snapshot function
- After enabling the metrics HTML server, users can also access metrics process-wide through '/' and '/metrics' endpoints. The server responds with a JSON representation of the `StreamStreamMetricsSnapshot` for each SiftStream instance, …
=> rust(feat): SiftStream Metrics
