sift-stack/sift

- CONTRIBUTING.md
- LICENSE
- SECURITY.md
Added licenses and various other policies.
> Licenses and policies

- README.md
- examples/python/README.md
- examples/python/requirements.txt
Use requirements.txt for example + README fixes.
> Python Docs Update

- protos/sift/runs/v2/runs.proto
Add `RunService_StopRun` and `RunService_DeleteRun`
> StopRun and DeleteRun RPCs

- examples/rust/ingestion_with_config/src/ingestion.rs
- examples/rust/ingestion_with_config/src/main.rs
> docs: Add helpful comments for rust ingestion example

- .github/workflows/ci.yaml
- python/examples/telemetry_config.example.yml
- python/lib/sift_internal/types.py
- python/lib/sift_py/ingestion/channel.py
- python/lib/sift_py/ingestion/config.py
- python/lib/sift_py/ingestion/config_test.py
- python/lib/sift_py/ingestion/ingestion_impl/ingest.py
- python/lib/sift_py/rule/__init__.py
- python/pyproject.toml
- python/scripts/dev
GA Actions for python tests + telemetry config test + example telemetry config.
> chore(python): testing setup

- python/pyproject.toml
Supposed name collisions on PyPI
> python(chore): package rename

- README.md
- python/README.md
- python/examples/ingestion_with_python_config/.env-example
- python/examples/ingestion_with_python_config/expression_modules/kinematics.yml
- python/examples/ingestion_with_python_config/expression_modules/string.yml
- python/examples/ingestion_with_python_config/main.py
- python/examples/ingestion_with_python_config/requirements.txt
- python/examples/ingestion_with_python_config/sample_data/sample_logs.txt
- python/examples/ingestion_with_python_config/simulator.py
- python/examples/ingestion_with_python_config/telemetry_config.py
- python/examples/ingestion_with_yaml_config/.env-example
- python/examples/ingestion_with_yaml_config/expression_modules/kinematics.yml
- python/examples/ingestion_with_yaml_config/expression_modules/string.yml
- python/examples/ingestion_with_yaml_config/main.py
- python/examples/ingestion_with_yaml_config/requirements.txt
- python/examples/ingestion_with_yaml_config/sample_data/sample_logs.txt
- python/examples/ingestion_with_yaml_config/simulator.py
- python/examples/ingestion_with_yaml_config/telemetry_config.py
- python/examples/ingestion_with_yaml_config/telemetry_configs/nostromo_lv_426.yml
Telemetry config examples using `sift-py`.
> python(chore): sift_py telemetry examples

- .gitignore
- README.md
- python/README.md
- python/docs/telemetry_config_schema.yml
- python/lib/sift_py/__init__.py
- python/lib/sift_py/grpc/__init__.py
- python/lib/sift_py/grpc/transport.py
- python/lib/sift_py/ingestion/__init__.py
- python/lib/sift_py/ingestion/channel.py
- python/lib/sift_py/ingestion/config/telemetry.py
- python/lib/sift_py/ingestion/config/yaml/spec.py
- python/lib/sift_py/ingestion/flow.py
- python/lib/sift_py/ingestion/rule/config.py
- python/lib/sift_py/ingestion/service.py
- python/pyproject.toml
- python/scripts/dev
Changes:
- README updates
- documentation updates + telemetry config yaml schema
- `pdoc` to build documentation locally
- Instructions on how to view documentation locally
> python(chore): pdoc + documentation

- go/go.mod
- go/go.sum
Needed for patching security vulnerability
> SIFT-2088: bump net package

- python/pyproject.toml
> python(chore): update pyproject version

- python/examples/ingestion_with_python_config/simulator.py
- python/examples/ingestion_with_yaml_config/simulator.py
> python(chore): update examples

- python/CHANGELOG.md
- python/pyproject.toml
Preparing for release candidate 3
> python(release): metadata for 0.1.0-rc.3

- python/CHANGELOG.md
- python/README.md
- python/pyproject.toml
- python/scripts/dev
Preparing for v0.1.0 release
Changes:
- Update project metadata and versions
- Change log update
- Readme update with links to online documentation
> python(release): preparing for v0.1.0

- python/lib/sift_grafana/sift_query_model.py
- python/pyproject.toml
This adds pydantic models for the json queries in the Sift Grafana plugin.
> add pydantic models for the sift grafana plugin queries

- python/pyproject.toml
Add `py.typed` files to each sub-package.
> python(chore): py.typed 

- protos/sift/annotation_logs/v1/annotation_logs.proto
- protos/sift/annotations/v1/annotations.proto
- protos/sift/assets/v1/assets.proto
- protos/sift/calculated_channels/v1/calculated_channels.proto
- protos/sift/channel_schemas/v1/channel_schemas.proto
- protos/sift/channels/v2/channels.proto
- protos/sift/common/type/v1/channel_bit_field_element.proto
- protos/sift/common/type/v1/channel_data_type.proto
- protos/sift/common/type/v1/channel_enum_type.proto
- protos/sift/common/type/v1/organization.proto
- protos/sift/common/type/v1/user.proto
- protos/sift/data/v1/data.proto
- protos/sift/ingest/v1/ingest.proto
- protos/sift/ingestion_configs/v1/ingestion_configs.proto
- protos/sift/notifications/v1/notifications.proto
- protos/sift/remote_files/v1/remote_files.proto
- protos/sift/rules/v1/rules.proto
- protos/sift/runs/v2/runs.proto
- protos/sift/saved_searches/v1/saved_searches.proto
- protos/sift/tags/v1/tags.proto
- protos/sift/users/v2/users.proto
- scripts/gen.sh
New protocol buffers and updates to existing protocol buffers, most notably:
- New saved searches protos to save search configurations on the home/overview page
- New remote files protos for programmatic file attachments
- Updates to rules proto for rule versioning
> feature(protos): new protos and various protos updates

- python/CHANGELOG.md
> python(chore): v0.2 changelog

- python/pyproject.toml
Bump version to `v0.2.0` in `pyproject.toml`.
> python(chore): bump version in pyproject.toml

- python/examples/ingestion_with_csv/main.py
- python/examples/ingestion_with_csv/requirements.txt
Add requirements.txt + other small changes
> python(chore): update example

- python/lib/sift_py/grpc/transport.py
Adds the ability to pipe custom gRPC metadata through `use_sift_channel`.
> python(feat): Add metadata arg to use_sift_channel

- python/CHANGELOG.md
- python/pyproject.toml
Bump version and changelog to prep for release
> python(chore): Bump version in pyproject and update changelog summary

- python/CHANGELOG.md
- python/pyproject.toml
Loosens dependency version requirements and 0.2.2 release prep.
> python(chore): loosen dependency version reqs

- python/examples/asset_agnostic_rules/.env-example
- python/examples/asset_agnostic_rules/main.py
- python/examples/asset_agnostic_rules/requirements.txt
- python/examples/asset_agnostic_rules/rule_modules/velocity.yml
- python/examples/asset_agnostic_rules/rule_modules/voltage.yml
- python/examples/asset_agnostic_rules/sample_data/sample_logs.txt
- python/examples/asset_agnostic_rules/simulator.py
- python/examples/asset_agnostic_rules/telemetry_configs/nostromo_lv_426.yml
- python/lib/sift_py/ingestion/_internal/channel.py
- python/lib/sift_py/ingestion/channel.py
- python/lib/sift_py/ingestion/config/yaml/load.py
- python/lib/sift_py/ingestion/rule/config.py
- python/lib/sift_py/rule/service.py
Allow rules to be configured outside of the context of a telemetry config.
> python(feature): asset agnostic rules

- python/CHANGELOG.md
- python/pyproject.toml
Changelog updates and version metadata in preparation for `v0.3.0-rc.1`.
> build: v0.3.0-rc.1 release prep

- .github/workflows/rust_ci.yaml
- .gitignore
- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/error/mod.rs
- rust/src/grpc/config.rs
- rust/src/grpc/interceptor.rs
- rust/src/grpc/mod.rs
- rust/src/lib.rs
Preparing for a v0.1.0 release
> rust(feature): grpc utils

- README.md
- buf_templates/buf.gen.cpp.yaml
- cpp/README.md
- cpp/ingestion/CMakeLists.txt
- cpp/ingestion/ingest.cc
- cpp/ping/CMakeLists.txt
- cpp/ping/ping.cc
https://dev.app.siftstack.com/share/6xgzIWX
> cpp: Add examples for C++

- README.md
- go/README.md
- rust/README.md
Add shields for docs + versions
> chore: readme doc links

- python/lib/sift_py/data_import/ch10.py
Also make setting the csv data columns simpler.
> python(feat): Allow uploading compressed ch10

- protos/sift/annotation_logs/v1/annotation_logs.proto
- protos/sift/annotations/v1/annotations.proto
- protos/sift/assets/v1/assets.proto
- protos/sift/calculated_channels/v2/calculated_channels.proto
- protos/sift/channels/v2/channels.proto
- protos/sift/common/type/v1/resource_ref.proto
- protos/sift/ingestion_configs/v1/ingestion_configs.proto
- protos/sift/notifications/v1/notifications.proto
- protos/sift/remote_files/v1/remote_files.proto
- protos/sift/report_templates/v1/report_templates.proto
- protos/sift/reports/v1/reports.proto
- protos/sift/rules/v1/rules.proto
- protos/sift/runs/v2/runs.proto
- protos/sift/saved_searches/v1/saved_searches.proto
- protos/sift/users/v2/users.proto
- protos/sift/views/v1/views.proto
Updated proto definitions for the latest changes to the Sift APIs
> SIFT-000: Updated protos for Sift APIs

- python/lib/sift_py/data_import/status.py
Before:
``` 
(venv) ~/code/sift/python/examples/data_import/csv/simple main $ python main.py
Traceback (most recent call last):
File "/Users/mjulien/code/sift/python/examples/data_import/csv/simple/main.py", line 37, in <module>
print(import_service.get_data_import())
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/Users/mjulien/code/sift/python/lib/sift_py/data_import/status.py", line 88, in get_data_import
data_import = DataImport(**data)
File "/Users/mjulien/code/sift/python/venv/lib/python3.13/site-packages/pydantic/main.py", line 212, in __init__
validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DataImport
ch10Config
Extra inputs are not permitted [type=extra_forbidden, input_value=None, …
```
> python: Fix bug in csv upload status

- python/CHANGELOG.md
- python/pyproject.toml
Updating CHANGELOG and bumping version for release.
> python(chore): v0.3.0 release prep

- makefile
- protos/sift/rule_evaluation/v1/rule_evaluation.proto
- protos/sift/rules/v1/rules.proto
- scripts/remove_go_pkg.sh
- scripts/sanitize.sh
Sanitizes unstable proto fields when copying, updated makefile to include this with removing the go package.
> proto: option to sanitize proto fields, update makefile

- python/lib/sift_py/_rest_test.py
- python/lib/sift_py/data_import/_csv_test.py
- python/lib/sift_py/data_import/_status_test.py
- python/lib/sift_py/data_import/_tdms_test.py
- python/lib/sift_py/data_import/csv.py
- python/lib/sift_py/data_import/status.py
- python/lib/sift_py/file_attachment/_internal/upload.py
- python/lib/sift_py/file_attachment/_service_test.py
- python/lib/sift_py/rest.py
Adds retrying on request failures for REST API calls.
> python(feat): retry for REST API calls

- python/CHANGELOG.md
- python/pyproject.toml
Update changelog and version number
> python(build): preparing for v0.4.2

- python/CHANGELOG.md
- python/pyproject.toml
Update pyproject version and changelog
> python(build): Release 0.5.0 prep

- protos/sift/api_keys/v2/api_keys.proto
Changes:
* added the ApiKeyOrganization endpoint
> protos: Adding ApiKeyOrganization endpoint

- python/lib/sift_py/data_import/tdms.py
Performed manual verification that strings were uploaded properly.
> python(bug): Add string support to TDMS upload

- rust/Cargo.lock
> rust(build): cargo lock update

- protos/sift/common/type/v1/user_defined_functions.proto
- protos/sift/rules/v1/rules.proto
- protos/sift/user_defined_functions/v1/user_defined_functions.proto
protos: add external flag to rules
* add external flag to rules
* add user defined functions and rules include function dependencies
* BatchUpdateRules includes rule identifiers of created rules
> Update Rules protos to include external rules and add User Defined Functions protos

- rust/CHANGELOG.md
- rust/Cargo.lock
- rust/Cargo.toml
> rust(build): v0.4.0 prep

- rust/CHANGELOG.md
- rust/Cargo.lock
- rust/Cargo.toml
Changelog + version bump for Rust v0.4.1
> rust(build): v0.4.1 prep

- rust/CHANGELOG.md
- rust/Cargo.lock
- rust/Cargo.toml
> rust(build): 0.4.2 prep

- protos/sift/common/type/v1/channel_enum_type.proto
- python/lib/sift/common/type/v1/channel_enum_type_pb2.py
- python/lib/sift/common/type/v1/channel_enum_type_pb2.pyi
- python/lib/sift_py/ingestion/channel.py
Updates channel_enum_type proto to include optional is_signed flag
> python(chore): Update channel_enum_type proto

- rust/crates/sift_stream/src/stream/builder.rs
- rust/crates/sift_stream/src/stream/mod.rs
- rust/crates/sift_stream/src/stream/mode/ingestion_config.rs
- rust/crates/sift_stream/src/stream/retry.rs
- rust/crates/sift_stream/src/stream/run.rs
Adds `attach_run` and `detach_run` to SiftStream
Attaching runs live tested in soak testing
> rust(feat): Attach and detach runs in SiftStream

- protos/sift/runs/v2/runs.proto
Adding the adhoc run creation to the Run service
> Add Adhoc Run Creation Endpoint
